config/routes.rb
Mail::Application.routes.draw do
  devise_for :admin_users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :hierarchies,only: [:index,:show,:index]

  resources :accounts

  devise_for :users
  get "home/index"
  resources :contacts

  root "home#index"

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :to, :presence => true
	validates :subject, :presence => true
	validates :body, :presence => true
	belongs_to :user
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :correct_user,   only: [:show,:edit, :update]
  
  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
    #@hierarchies=Hierarchy.all

  end

  def edit
  end

  def create    
     @contact = Contact.new(contact_params)
     attachment = params[:attachment]
     @contact.user_id =current_user.id
     @contact.user_name = current_user.account.kanjiname
     @contact.email = current_user.account.mail_addr
     addresses = params[:"addresses"]
     
     results = addresses.map {|address|
      email = @contact.clone
      email.to = address
      successed = email.save
      Message.hello(email,attachment).deliver if successed
      successed
    }

     respond_to do |format|
      if results.all?
         format.html { redirect_to @contact, notice: 'メールを送信しました。' }
         format.json { render action: 'show', status: :created, location: @contact }
       else
         format.html { render action: 'new' }
         format.json { render json: @contact.errors, status: :unprocessable_entity }
       end
     end
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    
    def set_contact
      @contact = Contact.find(params[:id])
    end
    def contact_params
      params.require(:contact).permit(:to, :reply, :subject, :body)
    end
    def attachment_params
      params.require(:attachment)
    end
    def correct_user
      @contact = Contact.find(params[:id])
      redirect_to root_path,:alert => '不正な操作です。' unless @contact.user_id == current_user.id
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
  <%= form_for(@contact, html: {class: "form-horizontal well"}) do |f| %>

  <% if @contact.errors.any? %>
  <div  class="alert alert-error">
    <a class="close" data-dismiss="alert" href="#">×</a>
    <h4 class="alert-heading"><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h4>
    <ul>
      <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  

  <label class="control-label" for>To
    <button class="btn btn-default" data-bind="click: addMailField">追加</button> 
  </label>
  <div class="controls" data-bind="foreach: mails">
    <div class="control-group">  
      <div>
        <input autocomplete="off" data-bind="value: $data, typeaheadStudent: true" id="inputEmail" name="addresses[]" placeholder="メールアドレス" size="42" type="email" class="inputaddress">
      </div>            
    </div>
  </div>

  
  <%  @contact.reply = current_user.account.mail_addr %>
  <div class="control-group">
    <%= f.label :reply , :class => "control-label" %>
    <div class="controls">
      <%= f.email_field :reply , :size => "42" %>
    </div>
  </div>

  <div class="control-group">
   <%= f.label :subject , :class => "control-label" %>
   <div class="controls">
    <%= f.text_field :subject ,:size => "42"  ,:placeholder => "件名"%>
  </div>
</div>

<div class="control-group">
  <%= f.label :body , :class => "control-label" %>
  <div class="controls">
    <%= f.text_area :body ,{:cols => "20" ,:rows => "10",:placeholder => "メール本文"}  %>
  </div>

  <div class="control-group">
    <%= f.label :file , :class => "control-label"%>
    <div class="controls">
      <%= f.file_field :attachment , {name: 'attachment',
        :id=>"file-input" 
      } %>
      <%#                               
      <input type="file" id="file-input" name="attachment" style="display: none;">
      <div class="input-prepend">
        <a class="btn" onclick="$('#file-input').click();"><i class="icon-folder-open"></i></a>
        <span id="cover" class="input-xlarge uneditable-input">select file</span>
      </div>
      %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit '送信する', :class => 'btn btn-primary' %>
    <%= link_to 'キャンセル', :back, :class => 'btn' %>
  </div>

</form>
<% end %>

<script>
$(function() {
  function MailFormViewModel() {
    var self = this;
    self.title = ko.observable('');
    self.body = ko.observable('');
    self.mails = ko.observableArray([ko.observable('')]);

    self.addMailField = function() {
      self.mails.push(ko.observable(''))
    }
  }

  window.mailForm = new MailFormViewModel();
  ko.applyBindings(mailForm, $('#mail_form')[0]);
});

ko.bindingHandlers['typeaheadStudent'] = {
  update: function(el) {
    $(el).typeahead({
      source: function(query, process) {
        $.getJSON("/accounts.json").then(function(accounts) {
          var addresses = $.map(accounts, function(account) { return account.mail_addr; });
          process(addresses);
        })
      }
    });
  }
};

</script>

app/views/contacts/edit.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contacts/index.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h2>送信済みメール</h2>
</div>
<% if current_user.contacts.any? %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:to) %></th>
      <th><%= model_class.human_attribute_name(:subject) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:reply) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% current_user.contacts.each do |contact| %>
      <tr>
        <td><%= contact.to %></td>
        <td><%= link_to contact.subject , contact_path(contact) %></td>
        <td><%= contact.body %></td>
        <td><%= contact.reply %></td>
        <td><%= simple_time(contact.created_at) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<p>送信済みメールはありません。</p>
<% end %>


<%= link_to "戻る", :back %>

app/views/contacts/new.html.erb
<%- model_class = Contact -%>
<% unless current_user.account.blank? %>
<div class="page-header">
	<h1>新規メール作成</h1>
</div>
<%= render :partial => 'form' %>
<% else %>
 <script type="text/javascript">
    window.location.href="/home/index"  // put your correct path in a string here
  </script>
<% end %>

app/views/contacts/show.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:to) %>:</strong></dt>
  <dd><%= @contact.to %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject) %>:</strong></dt>
  <dd><%= @contact.subject %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @contact.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @contact.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reply) %>:</strong></dt>
  <dd><%= @contact.reply %></dd>
  
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              contacts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_contact_path(@contact), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              contact_path(@contact),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>