config/routes.rb
Mail::Application.routes.draw do
  devise_for :admin_users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :hierarchies,only: [:index,:show,:index]

  resources :accounts

  devise_for :users
  get "home/index"
  resources :contacts

  root "home#index"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mail" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Mail</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
            <% if user_signed_in? %>
              <div class="btn-group">
                <a class="btn" href="#"><%= current_user.uid %></a>
                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "マイアカウント", '/home/index' %></li>
                  <li><%= link_to "ユーザ設定", edit_user_registration_path %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                </ul>
              </div>
            <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">メニュー</li>
              <% if user_signed_in? %>
              <li><%= link_to  'マイアカウント', '/home/index' %></li>
              <li><%= link_to 'ユーザ設定', edit_user_registration_path %></li>
              <li><%= link_to '送信済みメール一覧', contacts_path %></li>
              <li><%= link_to 'メール作成', new_contact_path %></li>
              <li><%= link_to 'アカウント一覧', accounts_path %></li>
              <li><%= link_to 'グループ一覧', hierarchies_path %></li>
              <% else %>
              <li><%= link_to "Admin Sign in", rails_admin.dashboard_path   %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->


    </div> <!-- /container -->

  </body>
</html>