config/routes.rb
Mail::Application.routes.draw do
  devise_for :admin_users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :hierarchies,only: [:index,:show,:index]

  resources :accounts

  devise_for :users
  get "home/index"
  resources :contacts

  root "home#index"

  

end

app/models/account.rb
class Account < ActiveRecord::Base
    belongs_to :user
    belongs_to :hierarchy
    validates :kanjiname, :presence => true
	validates :kananame, :presence => true
	validates :mail_addr, :presence => true,
						  :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ ,
                     	  :message => '不正な値です'}
	validates :user_id, :presence => true
	validates :hierarchy_id, :presence => true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :correct_user,   only: [:edit, :update]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user_id=current_user.id
    respond_to do |format|
      if @account.save
        format.html { redirect_to '/home/index', notice: 'アカウントが作成されました。' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)

        format.html { redirect_to '/home/index', notice: 'アカウントが更新されました。' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:kanjiname, :kananame, :mail_addr,:user_id, :hierarchy_id)
    end

    def correct_user
      @account = Account.find(params[:id])
      redirect_to root_path,:alert => '不正な操作です。' unless current_user.account.id == @account.id 
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for @account, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :kanjiname,label: '氏名' %>
  <%= f.input :kananame,label: 'ふりがな' %>
  <%= f.input :mail_addr, :as => :email,label: 'メールアドレス' %>
  <%#= f.input :hierarchy_id, , :collection => @hierarchies.map {|hierarchy| [hierarchy.gname, hierarchy.id]}, {:selected=>f.object.hierarchy_id}, :multiple => true, :size => @hierarchies.size %>
  <div class="control-group">
    <%= f.label '所属グループ' , :class => "control-label" %>
    <div class="controls">
   <%= f.collection_select :hierarchy_id, Hierarchy.all, :id, :gname %>  
  </div>

  <%= f.input :user_id, :as => :hidden %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to 'キャンセル',:back, class: 'btn' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1>アカウント編集</h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1>アカウント一覧</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>氏名</th>
      <th>ふりがな</th>
      <th>メールアドレス</th>
      <th>グループ名</th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.kanjiname, account_path(account) %></td>
        <td><%= account.kananame %></td>
        <td><%= account.mail_addr %></td>
        <td><% unless account.hierarchy.nil? %>
             <%= link_to account.hierarchy.gname, hierarchy_path(account.hierarchy) %>
            <% else %>
              未所属
            <% end %>
        </td> 
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Back", :back %>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1>新規アカウント</h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1>アカウント情報</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>氏名:</strong></dt>
  <dd><%= @account.kanjiname %></dd>
  <dt><strong>ふりがな:</strong></dt>
  <dd><%= @account.kananame %></dd>
  <dt><strong>メールアドレス:</strong></dt>
  <dd><%= @account.mail_addr %></dd>
  <dt><strong>所属グループ:</strong></dt>
  <dd><%= @account.hierarchy.gname %></dd>
  <dt><strong><%#= model_class.human_attribute_name(:hierarchy_id) %></strong></dt>
  <dd><%#= @account.hierarchy_id %></dd>

</dl>

<%= link_to "戻る", :back,:class =>'btn' %>